version: 0.2

phases:
  runtime-versions:
    nodejs: 10
  build:
    commands:
      - . ./ecs/build.sh

  post_build:
    commands:
      - . ./ecs/post_build.sh

artifacts:
  files:
    - ecs/*
    - buildspec.yml
    - docker.tag
    