version: 0.2

phases:
  build:
    commands:
      - . ./ecs.sh

  post_build:
    commands:
      - . ./ecs/post_build.sh

artifacts:
  files:
    - ecs.sh
    - ecs/*
    - buildspec.yml
    - docker.tag
